"""add roles and permissions

Revision ID: 8b15ee1b5d77
Revises: 7307ace12603
Create Date: 2026-07-28 19:57:05.872982

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8b15ee1b5d77'
down_revision: Union[str, Sequence[str], None] = '7307ace12603'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('roles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('role_id', sa.Integer(), nullable=False),
    sa.Column('module', sa.String(length=50), nullable=False),
    sa.Column('can_view', sa.Boolean(), nullable=False),
    sa.Column('can_add', sa.Boolean(), nullable=False),
    sa.Column('can_edit', sa.Boolean(), nullable=False),
    sa.Column('can_delete', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('role_id', 'module', name='uq_role_module')
    )
    # batch_alter_table so this also works on SQLite (used only for local
    # verification), not just MySQL — on MySQL it still just emits a plain
    # ALTER TABLE, no behavior change.
    with op.batch_alter_table('users') as batch_op:
        batch_op.add_column(sa.Column('permission_role_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_users_permission_role_id', 'roles', ['permission_role_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users') as batch_op:
        batch_op.drop_constraint('fk_users_permission_role_id', type_='foreignkey')
        batch_op.drop_column('permission_role_id')
    op.drop_table('role_permissions')
    op.drop_table('roles')
    # ### end Alembic commands ###
