"""add item hsn code and gst percentage

Revision ID: e92bc1274286
Revises: 8b15ee1b5d77
Create Date: 2026-07-28 20:29:19.049632

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e92bc1274286'
down_revision: Union[str, Sequence[str], None] = '8b15ee1b5d77'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('hsn_code', sa.String(length=10), nullable=True))
    op.add_column('items', sa.Column('gst_percentage', sa.Numeric(precision=5, scale=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('items', 'gst_percentage')
    op.drop_column('items', 'hsn_code')
    # ### end Alembic commands ###
